name: CI

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        id: setup_nodejs
        with:
          node-version-file: '.tool-versions'
      - uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: ${{ runner.arch }}-${{ runner.os }}-node-${{ steps.setup_nodejs.outputs.node-version }}-npm-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/cache@v4
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: |
            ~/.npm
            ~/.cache/Cypress
            ~/.cache/ms-playwright
          key: ${{ runner.arch }}-${{ runner.os }}-node-${{ steps.setup_nodejs.outputs.node-version }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.arch }}-${{ runner.os }}-node-${{ steps.setup_nodejs.outputs.node-version }}-npm-
      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: ${{ github.base_ref }}
      - name: Setup Nx Cloud
        run: npx nx-cloud start-ci-run --distribute-on="3 custom-linux-medium-js"
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - run: npx nx affected --target=build,test,lint --configuration=ci
